apiVersion: v1
kind: Service
metadata:
  name: my-nextjs-app-service
spec:
  selector:
    app: my-nextjs-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
